project:
  type: book
  output-dir: docs

comments:
  hypothesis: true


book:
  title: "General Surgery GOGv2"
  author: "C Varghese"
  chapters:
    - index.qmd

format:
  html:
    theme: simplex
    font:
      text: "Georgia, serif"         # A classic serif for text
      headings: "Georgia, serif"     # Serif headings for a traditional look
      code: "Courier New, monospace" # Code blocks in a monospaced font
